apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/parca-dev/parca/releases/download/v0.25.0/kubernetes-manifest.yaml
- https://github.com/parca-dev/parca-agent/releases/download/v0.44.1/kubernetes-manifest.yaml
